import { Game } from './types';

// INSTRUCTIONS FOR USER:
// 1. To add a local game, place the game folder in your public directory (e.g., 'public/games/my-game/').
// 2. Set the 'path' to '/games/my-game/index.html'.
// 3. To add a hosted game (like the ones below), just set the 'path' to the full URL (https://...).
// 4. Games are sorted by releaseDate in descending order (newest first).

export const GAMES_LIST: Game[] = [
  {
    id: 'ppt-master',
    title: '我在发布会现场改PPT',
    description: '老板说的和PPT上不一样怎么办？还愣着干嘛？赶紧改啊！',
    coverUrl: 'https://placehold.co/400x600/2563eb/white?text=PPT+Master',
    path: 'https://pptmaster.netlify.app/',
    tags: ['解谜', '办公'],
    releaseDate: '2025-08-09',
  },
  {
    id: 'wudao',
    title: '悟道',
    description: '悟道之旅。在禅意氛围中体验哲学深度。',
    coverUrl: 'https://placehold.co/400x600/44403c/white?text=Wu+Dao',
    path: 'https://seedao.netlify.app/',
    tags: ['禅意', '哲学'],
    releaseDate: '2025-07-22',
  },
  {
    id: 'kiss-camera',
    title: '我在Coldplay现场做导播',
    description: '演唱会摄像师模拟。在人群中捕捉精彩瞬间。',
    coverUrl: 'https://placehold.co/400x600/ec4899/white?text=Coldplay+Camera',
    path: 'https://seedao.netlify.app/',
    tags: ['街机', '派对'],
    releaseDate: '2025-07-25',
  },
  {
    id: 'dish-battle',
    title: '今天谁洗碗',
    description: '关于工作生活平衡的互动故事。多重结局等你探索。',
    coverUrl: 'https://placehold.co/400x600/64748b/white?text=Dish+Battle',
    path: 'https://whowillwash.netlify.app/',
    tags: ['剧情', '生活'],
    releaseDate: '2025-07-12',
  },
  {
    id: 'detective',
    title: '幻听神探',
    description: '拥有特殊能力的侦探。聆听物品说话，解决离奇案件。',
    coverUrl: 'https://placehold.co/400x600/1f2937/white?text=Detective',
    path: 'https://itemdetective.netlify.app/',
    tags: ['推理', '解谜'],
    releaseDate: '2025-07-03',
  },
  {
    id: 'key-choice',
    title: '关键选择',
    description: '选择至关重要。每个决定都将塑造你的命运。',
    coverUrl: 'https://placehold.co/400x600/e11d48/FFF?text=Key+Choice',
    path: 'https://keychoice.netlify.app/',
    tags: ['剧情', '选择'],
    releaseDate: '2025-06-20',
  },
  {
    id: 'perfect-date',
    title: '完美约会',
    description: '模拟现代约会的复杂性。尽量别破坏气氛。',
    coverUrl: 'https://placehold.co/400x600/pink/black?text=Perfect+Date',
    path: 'https://perfectdate.netlify.app/',
    tags: ['模拟', '恋爱'],
    releaseDate: '2025-06-13',
  },
  {
    id: 'mask-shop',
    title: '假面商店',
    description: '经营神秘的面具商店。为每位顾客找到合适的面具。',
    coverUrl: 'https://placehold.co/400x600/4c1d95/white?text=Mask+Shop',
    path: 'https://desiremaskshop.netlify.app/',
    tags: ['模拟', '神秘'],
    releaseDate: '2025-06-06',
  },
  {
    id: 'indie-dev',
    title: '独游发展国',
    description: '独立游戏开发模拟器。带领团队克服挑战，打造爆款游戏。',
    coverUrl: 'https://placehold.co/400x600/1e293b/white?text=Indie+Dev',
    path: 'https://endearing-lolly-ecae68.netlify.app/',
    tags: ['经营', 'RPG'],
    releaseDate: '2025-05-31',
  },
  {
    id: 'dinner-sim',
    title: '饭局模拟器',
    description: '在正式晚宴的社交雷区中穿行。礼仪就是一切。',
    coverUrl: 'https://placehold.co/400x600/f59e0b/black?text=Dinner+Sim',
    path: 'https://abigdeal.netlify.app/',
    tags: ['社交', '模拟'],
    releaseDate: '2025-05-24',
  },
  {
    id: 'light-shadow',
    title: '光影对决',
    description: '光与影的视觉对决。快节奏的街机动作游戏。',
    coverUrl: 'https://placehold.co/400x600/black/white?text=Light+Shadow',
    path: 'https://clairobscur.netlify.app/',
    tags: ['动作', '街机'],
    releaseDate: '2025-05-15',
  },
  {
    id: 'tony',
    title: '剪刀手托尼',
    description: '成为理发师托尼。理解顾客需求，选择合适的发型。',
    coverUrl: 'https://placehold.co/400x600/0ea5e9/white?text=Tony+Barber',
    path: 'https://amazingtony.netlify.app/',
    tags: ['模拟', '休闲'],
    releaseDate: '2025-05-09',
  },
  {
    id: 'subway',
    title: '地铁睡神',
    description: '在地铁上打瞌睡时保持平衡。别摔倒，别坐过站！',
    coverUrl: 'https://placehold.co/400x600/10b981/white?text=Subway+Sleeper',
    path: 'https://subwaygirl.netlify.app/',
    tags: ['平衡', '街机'],
    releaseDate: '2025-05-01',
  },
  {
    id: 'bus',
    title: '田园巴士',
    description: '驾驶乡村路线。接送乘客，欣赏风景。',
    coverUrl: 'https://placehold.co/400x600/84cc16/black?text=Country+Bus',
    path: 'https://countrybus.netlify.app/',
    tags: ['驾驶', '模拟'],
    releaseDate: '2025-04-25',
  },
  {
    id: 'raining',
    title: '雨中修行',
    description: '在文字雨中漫步。吸收智慧，躲避负能量。',
    coverUrl: 'https://placehold.co/400x600/3b82f6/white?text=Raining+Words',
    path: 'https://rainingwords.netlify.app/',
    tags: ['禅意', '反应'],
    releaseDate: '2025-04-17',
  },
  {
    id: 'stream',
    title: '拯救直播',
    description: '管理混乱的直播间。让观众开心，让房管清醒。',
    coverUrl: 'https://placehold.co/400x600/8b5cf6/white?text=Save+Stream',
    path: 'https://savethestream.netlify.app/',
    tags: ['管理', '街机'],
    releaseDate: '2025-04-11',
  },
  {
    id: 'flyer',
    title: '传单大师',
    description: '给路人发传单。避免被拒绝，坚持到底。',
    coverUrl: 'https://placehold.co/400x600/f43f5e/white?text=Flyer+Master',
    path: 'https://superflyer.netlify.app/',
    tags: ['动作', '街机'],
    releaseDate: '2025-04-03',
  },
  {
    id: 'elevator',
    title: '电梯按摩',
    description: '帮助疲惫的上班族在电梯里放松。戳破负面情绪气泡。',
    coverUrl: 'https://placehold.co/400x600/a8a29e/black?text=Elevator+Massage',
    path: 'https://elevatormassage.netlify.app/',
    tags: ['解谜', '休闲'],
    releaseDate: '2025-03-25',
  },
  {
    id: 'rhythm',
    title: '节奏人生',
    description: '跟随生活的节拍。一段关于日常生活的音乐旅程。',
    coverUrl: 'https://placehold.co/400x600/db2777/white?text=Life+Rhythm',
    path: 'https://liferythm.netlify.app/',
    tags: ['音乐', '节奏'],
    releaseDate: '2025-03-20',
  },
  {
    id: 'delivery',
    title: '快递搁浅',
    description: '物理模拟送货游戏。在摩托车上保持包裹平衡，送达目的地。',
    coverUrl: 'https://placehold.co/400x600/f97316/white?text=Delivery',
    path: 'https://superdeliver.netlify.app/',
    tags: ['物理', '模拟'],
    releaseDate: '2025-03-13',
  },
  {
    id: 'coffee',
    title: '快手咖啡师',
    description: '快节奏咖啡店模拟器。制作饮品，服务顾客，赚取小费。',
    coverUrl: 'https://placehold.co/400x600/78350f/white?text=Coffee+Rush',
    path: 'https://coffeerusher.netlify.app/',
    tags: ['模拟', '休闲'],
    releaseDate: '2025-03-10',
  },
];
