import { Game } from './types';

// INSTRUCTIONS FOR USER:
// 1. To add a local game, place the game folder in your public directory (e.g., 'public/games/my-game/').
// 2. Set the 'path' to '/games/my-game/index.html'.
// 3. To add a hosted game (like the ones below), just set the 'path' to the full URL (https://...).
// 4. Games are sorted by releaseDate in descending order (newest first).

export const GAMES_LIST: Game[] = [
  {
    id: 'ppt-master',
    title: '我在发布会现场改PPT',
    titleEn: 'PPT Master',
    description: '老板说的和PPT上不一样怎么办？还愣着干嘛？赶紧改啊！',
    coverUrl: 'https://placehold.co/400x600/2563eb/white?text=PPT+Master',
    path: 'https://pptmaster.netlify.app/',
    tags: ['解谜', '办公'],
    releaseDate: '2025-08-09',
    story: '"老板说的和ppt上不一样怎么办？""还愣着干嘛？赶紧改啊！"——GPT发布会有感。',
  },
  {
    id: 'wudao',
    title: '悟道',
    titleEn: 'Wu Dao',
    description: '悟道之旅。在禅意氛围中体验哲学深度。',
    coverUrl: 'https://placehold.co/400x600/44403c/white?text=Wu+Dao',
    path: 'https://seedao.netlify.app/',
    tags: ['禅意', '哲学'],
    releaseDate: '2025-07-22',
    story: '受邀参加一个比赛，主题是"中国传统文化"，着实有点积累不够，只能玩抽象了！不知道你能体会得到吗？（最后果然陪跑了）',
  },
  {
    id: 'kiss-camera',
    title: '我在Coldplay现场做导播',
    titleEn: 'Coldplay Camera',
    description: '演唱会摄像师模拟。在人群中捕捉精彩瞬间。',
    coverUrl: 'https://placehold.co/400x600/ec4899/white?text=Coldplay+Camera',
    path: 'https://seedao.netlify.app/',
    tags: ['街机', '派对'],
    releaseDate: '2025-07-25',
    story: '作为一名职业摄影师，什么该拍、什么不该拍，你…你为什么要在乎呢？本周遭遇野卡被喝茶，cursor无法续订。机缘尝试了Kimi新发的K2模型，无缝接入claude code，没想到挺能打的，期待多模态版本，祝国产模型越来越强！',
  },
  {
    id: 'dish-battle',
    title: '今天谁洗碗',
    titleEn: 'Dish Battle',
    description: '关于工作生活平衡的互动故事。多重结局等你探索。',
    coverUrl: 'https://placehold.co/400x600/64748b/white?text=Dish+Battle',
    path: 'https://whowillwash.netlify.app/',
    tags: ['剧情', '生活'],
    releaseDate: '2025-07-12',
    story: '偷偷告诉你：我有个朋友，某天跟我讲了个故事…千万不要告诉他！开玩笑的，这个游戏是我在John Yorke Story课程的一次课后作业。',
  },
  {
    id: 'detective',
    title: '幻听神探',
    titleEn: 'Item Detective',
    description: '拥有特殊能力的侦探。聆听物品说话，解决离奇案件。',
    coverUrl: 'https://placehold.co/400x600/1f2937/white?text=Detective',
    path: 'https://itemdetective.netlify.app/',
    tags: ['推理', '解谜'],
    releaseDate: '2025-07-03',
    story: '作为一个能够听见物品说话的超能力神探，你能还原案件、找出真凶吗？"Everything is Alive."是上周CiGA Gamejam的比赛主题，虽然没机会参加比赛，大脑却无法避免被如此有趣的主题入侵。无奈48小时实在掏不出来，强力队友也来不及喊，就做个丐中丐的小游戏吧！',
  },
  {
    id: 'key-choice',
    title: '关键选择',
    titleEn: 'Key Choice',
    description: '选择至关重要。每个决定都将塑造你的命运。',
    coverUrl: 'https://placehold.co/400x600/e11d48/FFF?text=Key+Choice',
    path: 'https://keychoice.netlify.app/',
    tags: ['剧情', '选择'],
    releaseDate: '2025-06-20',
    story: '受《多重人生》影响做的荒诞小游戏。胡编乱造，仅供娱乐。如有雷同，纯属雷同。',
  },
  {
    id: 'perfect-date',
    title: '完美约会',
    titleEn: 'Perfect Date',
    description: '模拟现代约会的复杂性。尽量别破坏气氛。',
    coverUrl: 'https://placehold.co/400x600/pink/black?text=Perfect+Date',
    path: 'https://perfectdate.netlify.app/',
    tags: ['模拟', '恋爱'],
    releaseDate: '2025-06-13',
    story: '还记得第一次约会的心跳回忆吗？有过因为不知道说什么而尴尬的经历吗？或者，你早已将《约会话术大全》背的滚瓜烂熟？来试试吧，在话题的量子空间里，好结局只有一个，但"打捞"它不只需要耐心。灵感来自欧亨利的《公主与美洲狮》',
  },
  {
    id: 'mask-shop',
    title: '假面商店',
    titleEn: 'Mask Shop',
    description: '经营神秘的面具商店。为每位顾客找到合适的面具。',
    coverUrl: 'https://placehold.co/400x600/4c1d95/white?text=Mask+Shop',
    path: 'https://desiremaskshop.netlify.app/',
    tags: ['模拟', '神秘'],
    releaseDate: '2025-06-06',
    story: '一个鲜活的主角少不了欲望，而欲望的背后是愿望(want)和需求(need)。愿望，是他们自以为需要的，需求，才是他们真正欠缺的，而这种欠缺，造就了他们的缺陷(flaw)。因此，不少旅途中角色会提醒故事的主角："别管那些愿望了，它根本不重要！"虽然故事的最后，主角终将意识到这个事实。但假若没有愿望，故事就不会开始。不是么？',
  },
  {
    id: 'indie-dev',
    title: '独游发展国',
    titleEn: 'Indie Dev',
    description: '独立游戏开发模拟器。带领团队克服挑战，打造爆款游戏。',
    coverUrl: 'https://placehold.co/400x600/1e293b/white?text=Indie+Dev',
    path: 'https://endearing-lolly-ecae68.netlify.app/',
    tags: ['经营', 'RPG'],
    releaseDate: '2025-05-31',
    story: '用ai生成文本就是生成一时爽，改起来真要命。快100个随机事件…实在是改不动了，大家就忍受一下ai味吧…',
  },
  {
    id: 'dinner-sim',
    title: '饭局模拟器',
    titleEn: 'Dinner Sim',
    description: '在正式晚宴的社交雷区中穿行。礼仪就是一切。',
    coverUrl: 'https://placehold.co/400x600/f59e0b/black?text=Dinner+Sim',
    path: 'https://abigdeal.netlify.app/',
    tags: ['社交', '模拟'],
    releaseDate: '2025-05-24',
    story: '感觉个人风格已经收敛成需要运用社会推理能力破解游戏机制的核心玩法，这次的题材源于目睹同事因为安排了错误的人参加tob饭局导致业务受阻被老板喷了一顿...所以，你能谈成这个饭局么？',
  },
  {
    id: 'light-shadow',
    title: '光影对决',
    titleEn: 'Clair Obscur',
    description: '光与影的视觉对决。快节奏的街机动作游戏。',
    coverUrl: 'https://placehold.co/400x600/black/white?text=Light+Shadow',
    path: 'https://clairobscur.netlify.app/',
    tags: ['动作', '街机'],
    releaseDate: '2025-05-15',
    story: '33号远征队的后劲十足，忍不住做了个"全损版"小游戏。如果你觉得好玩，赶紧拿起身边的电话订购吧！',
  },
  {
    id: 'tony',
    title: '剪刀手托尼',
    titleEn: 'Tony Barber',
    description: '成为理发师托尼。理解顾客需求，选择合适的发型。',
    coverUrl: 'https://placehold.co/400x600/0ea5e9/white?text=Tony+Barber',
    path: 'https://amazingtony.netlify.app/',
    tags: ['模拟', '休闲'],
    releaseDate: '2025-05-09',
    story: '由于跟托尼老师的时间几次没对上，我的发型逐渐从"抽象派"进阶成"行为艺术"，不得不就近找个托尼老师紧急处理。"想怎么剪？"接待我的是店主，留着稀疏平常的短发，疲惫的撇了一眼我头顶的艺术品。"能还原之前的发型吗？"我想这踢馆般的要求能提一提他的精气。他纹丝不动，用梳子在我头顶飞速游走…偏分方式、长短分布、疏密层次…2个月的变化在他眼中倒叙播放…仿佛一名老派侦探正在还原犯罪现场。"问题不大！"他几秒钟后开口，给了我一个肯定的答复，眼神中透露着"作案手法已看破"般的自信。最终，神探托尼完成了95%的还原程。唯一的悬案是左鬓角一缕倔强的发丝：它究竟该归位到头顶的"平原"，还是脑后的"丘陵"？目前证据链显示，它绝对不属于"左侧边陲"。推门离开时，我撇见他坐在前台闭目养神，不知是在游历思维殿堂、还是在等待下一个"委托人"的出现。',
  },
  {
    id: 'subway',
    title: '地铁睡神',
    titleEn: 'Subway Sleeper',
    description: '在地铁上打瞌睡时保持平衡。别摔倒，别坐过站！',
    coverUrl: 'https://placehold.co/400x600/10b981/white?text=Subway+Sleeper',
    path: 'https://subwaygirl.netlify.app/',
    tags: ['平衡', '街机'],
    releaseDate: '2025-05-01',
    story: '最近开始封印方向盘，作为观测者，重新体验地铁这个独特的"舞台"。是否能练就福尔摩斯的演绎法尚未可知，但搜集形形色色的人设是再好不过了。我曾以为，高峰期的乘客通常分为两个流派：站着的手机流和坐着的睡觉流。但前天我遇到了一个例外，他坐得笔挺，以响亮的鼾声为律动，踩点刷着短视频。这是一次伟大的发现，证明叠加态没有因为观测者的测量而坍缩！话说回来，自己坐地铁睡觉的经历也不在少数，有几次还不小心躺到了隔壁的身上，搞得现场十分尴尬。之后为了避免这种情况，我经常会守着最靠边的位置。现在想来，这种体验还挺有趣的，多亏了重新坐地铁才找回来。你是不是也和我一样，有过类似的体验呢？',
  },
  {
    id: 'bus',
    title: '田园巴士',
    titleEn: 'Country Bus',
    description: '驾驶乡村路线。接送乘客，欣赏风景。',
    coverUrl: 'https://placehold.co/400x600/84cc16/black?text=Country+Bus',
    path: 'https://countrybus.netlify.app/',
    tags: ['驾驶', '模拟'],
    releaseDate: '2025-04-25',
    story: '偶然的机会坐了一次公交车，相比开车一切都慢了下来。车窗变成了荧幕，上演着街边发生的小故事，记忆被拉回10年前刚来深圳的日子。那时天天公交上下班，却没留下任何相似的记忆，估计是满脑子都在想工作的事情吧！我一直是个目的性极强的人，也因此忽略了不少过程的美好。于是我想把坐公交的体验游戏化，接着意外在b站发现了70年代售票员任玉琢的故事，记忆被进一步拉回到20年前——一个乘客们会在公交车上聊天的年代，然而这种现象却随着文明的"进步"消失了…所以，就用游戏的方式记录一下吧。以后有机会，捡起来做成完整的独游。',
  },
  {
    id: 'raining',
    title: '雨中修行',
    titleEn: 'Raining Words',
    description: '在文字雨中漫步。吸收智慧，躲避负能量。',
    coverUrl: 'https://placehold.co/400x600/3b82f6/white?text=Raining+Words',
    path: 'https://rainingwords.netlify.app/',
    tags: ['禅意', '反应'],
    releaseDate: '2025-04-17',
    story: '何同学肯定没想到"真诚"换来的是塌方，但同时也解锁了一次重要的"系统"升级。在这个由信息和能量构成的世界中，每个自我都是在和世界的碰撞中形成的。善意的声音会帮助我们成长，恶意的声音会阻碍我们生存，学会有选择的倾听和回避，是每个人的雨中修行。',
  },
  {
    id: 'stream',
    title: '拯救直播',
    titleEn: 'Save The Stream',
    description: '管理混乱的直播间。让观众开心，让房管清醒。',
    coverUrl: 'https://placehold.co/400x600/8b5cf6/white?text=Save+Stream',
    path: 'https://savethestream.netlify.app/',
    tags: ['管理', '街机'],
    releaseDate: '2025-04-11',
    story: '上周speed中国行闹的沸沸扬扬，深圳场的时候特地去油管看了一下，刚好看到卤鹅叔和speed在车内语言不通的场景。事先不知道卤鹅哥的故事，还误以为深圳连个靠谱的翻译都没有，事后听说了他的"追星故事"。看着油管评论全是"this uncle save the stream"，而与他同框的长沙文和友老板就走向了完全相反的方向。但是在取景框之外的他俩，又真的有这么大差别么？于是有了这次的创作灵感。这次你将扮演美食主播的御用摄影师，受邀对某个西餐厅进行直播宣传活动。你镜头下的内容不仅影响着流量，还影响着舆论、店铺商誉以及直播的故事走向。没错，这是一个通过镜头来选择故事走向的互动叙事！终于在sidequest里做了main quest事，不由的多花了很多时间，希望感兴趣的朋友喜欢！',
  },
  {
    id: 'flyer',
    title: '传单大师',
    titleEn: 'Flyer Master',
    description: '给路人发传单。避免被拒绝，坚持到底。',
    coverUrl: 'https://placehold.co/400x600/f43f5e/white?text=Flyer+Master',
    path: 'https://superflyer.netlify.app/',
    tags: ['动作', '街机'],
    releaseDate: '2025-04-03',
    story: '昨天在星巴克目睹一件趣事：一个小哥挨桌投递脱单app的广告传单，随后另一名服务员面无表情的挨桌拿起传单揉成一团丢进垃圾车，一眨眼的功夫就抹去了传单小哥来过的痕迹。一面是顶着笑脸的服务员，另一面是拦在传单小哥面前的大boss，一瞬间这种反讽的感觉戳中了自己的high点，那就以传单小哥的视角做一个小游戏吧！不过，最终想法并没有往"传单小哥大战服务员"的方向收敛，但情绪表达上也是达成预期了。',
  },
  {
    id: 'elevator',
    title: '电梯按摩',
    titleEn: 'Elevator Massage',
    description: '帮助疲惫的上班族在电梯里放松。戳破负面情绪气泡。',
    coverUrl: 'https://placehold.co/400x600/a8a29e/black?text=Elevator+Massage',
    path: 'https://elevatormassage.netlify.app/',
    tags: ['解谜', '休闲'],
    releaseDate: '2025-03-25',
    story: '最近《人生切割术》中毒太深，电梯间切换人格这个设定实在太妙，于是东施效颦了一下。这次你可以角色扮演一部会心灵按摩的电梯，还在等什么呢？',
  },
  {
    id: 'rhythm',
    title: '节奏人生',
    titleEn: 'Life Rhythm',
    description: '跟随生活的节拍。一段关于日常生活的音乐旅程。',
    coverUrl: 'https://placehold.co/400x600/db2777/white?text=Life+Rhythm',
    path: 'https://liferythm.netlify.app/',
    tags: ['音乐', '节奏'],
    releaseDate: '2025-03-20',
    story: '创作动机是两天前刷到《降临》的电影解说，想起一句鸡汤"老天让每天不断重复，是为了让我们更容易发现其中的不同。"那么，能不能做一个表达类似理念的游戏呢？脑中迅速闪过了上周末无聊在车机上玩的TRAX，那是一个随便乱戳都可以出现有趣音乐的APP。于是，"日常计划"和"音频混响"就这么被缝合到了一起！',
  },
  {
    id: 'delivery',
    title: '快递搁浅',
    titleEn: 'Delivery Stranding',
    description: '物理模拟送货游戏。在摩托车上保持包裹平衡，送达目的地。',
    coverUrl: 'https://placehold.co/400x600/f97316/white?text=Delivery',
    path: 'https://superdeliver.netlify.app/',
    tags: ['物理', '模拟'],
    releaseDate: '2025-03-13',
    story: '《死亡搁浅2》上周发布了最新预告片，居然还要等3个月太难熬了！忍不住做一个致敬小游戏表达一下激动的心情～这次游戏有点复杂，和AI聊了100多句，不知不觉加了很多功能，开发耗时10个小时左右，美术素材都是用即梦生成的。起初想世界观和美术都致敬原作，但中途突然觉得如果能描写普通快递小哥的工作感受可能会更有趣一些，于是临时调整了方向。（终于不怕程序员和美术吐槽策划改方向了哈哈）。',
  },
  {
    id: 'coffee',
    title: '快手咖啡师',
    titleEn: 'Coffee Rush',
    description: '快节奏咖啡店模拟器。制作饮品，服务顾客，赚取小费。',
    coverUrl: 'https://placehold.co/400x600/78350f/white?text=Coffee+Rush',
    path: 'https://coffeerusher.netlify.app/',
    tags: ['模拟', '休闲'],
    releaseDate: '2025-03-10',
    story: '用Claude做的第一个游戏，为了改Claude生成的代码的bug，不知不觉在cursor里面上了头。一边喝咖啡一边按tab键，也许就是未来的退休生活？',
  },
];
